In [4]:
import re
import pandas as pd

In [2]:
df = pd.read_csv('/Users/renatoboemer/code/boemer00/Netflix/raw_data/df_train.csv')

In [3]:
df.head(3)

,avg_review_score,n_reviews,year,title,Title,Year,Rated,Released,Runtime,Genre,...,Response,Internet Movie Database,Index_match,DVD,BoxOffice,Production,Website,Rotten Tomatoes,Metacritic,Ratings
0,3.749543,547,2003,Dinosaur Planet,Dinosaur Planet,2003,NaN,14-Dec-03,50 min,"Documentary, Animation, Family",...,True,7.7/10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.641153,2012,1997,Character,Character,1997,R,27-Mar-98,122 min,"Crime, Drama, Mystery",...,True,7.7/10,3,04-Feb-03,"$623,983",Almerica Film,NaN,92%,NaN,NaN
2,3.084396,1019,1997,Sick,Sick,1997,Not Rated,07-Nov-97,90 min,Documentary,...,True,7.5/10,6,15-Feb-17,"$116,806",Sick-the Life and Death of Bob Flanagan-Superm...,NaN,91%,82/100,NaN

In [6]:
class CleanReleasedEncoder(x):
            
    def transform(x, y=None):
        final =np.array([re.findall("[a-zA-Z]+",row[0])for row in x])
        return final

    def fit(x, y=None):
        return x

NameError: name 'x' is not defined

In [ ]:
def set_pipeline(self):
        pipe_language_features = Pipeline([('country', SimpleImputer(strategy='constant', fill_value="unknown")),
                                           ('language_encoder', CleanLanguageEncoder())])